import {TrialRun} from '../../redux/reducers/participants';

export enum Shape {
  Plus = 'Plus',
  Star = 'Star',
  Triangle = 'Triangle',
  Circle = 'Circle',
}

export enum Pattern {
  Color = 'Color',
  Shape = 'Shape',
  Number = 'Number',
}

export interface CardRule {
  shape: Shape;
  color: number;
  count: number;
  correctAnswer: number;
  pattern: Pattern;
}
export const CardRules: Record<TrialRun, CardRule[]> = {
  [TrialRun.Ground]: [
    {
      shape: Shape.Plus,
      color: 4,
      count: 3,
      correctAnswer: 4,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Star,
      color: 1,
      count: 1,
      correctAnswer: 1,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Triangle,
      color: 3,
      count: 2,
      correctAnswer: 3,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Circle,
      color: 3,
      count: 3,
      correctAnswer: 3,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Plus,
      color: 3,
      count: 4,
      correctAnswer: 3,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Circle,
      color: 2,
      count: 2,
      correctAnswer: 2,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Circle,
      color: 1,
      count: 3,
      correctAnswer: 1,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Plus,
      color: 4,
      count: 1,
      correctAnswer: 3,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Star,
      color: 2,
      count: 1,
      correctAnswer: 4,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Star,
      color: 4,
      count: 3,
      correctAnswer: 4,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Triangle,
      color: 3,
      count: 4,
      correctAnswer: 2,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Star,
      color: 4,
      count: 3,
      correctAnswer: 4,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Triangle,
      color: 2,
      count: 3,
      correctAnswer: 2,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Star,
      color: 3,
      count: 1,
      correctAnswer: 3,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Circle,
      color: 2,
      count: 4,
      correctAnswer: 2,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Circle,
      color: 1,
      count: 4,
      correctAnswer: 1,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Triangle,
      color: 3,
      count: 2,
      correctAnswer: 3,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Star,
      color: 1,
      count: 3,
      correctAnswer: 1,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Triangle,
      color: 1,
      count: 1,
      correctAnswer: 1,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Circle,
      color: 1,
      count: 1,
      correctAnswer: 1,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Star,
      color: 3,
      count: 2,
      correctAnswer: 2,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Star,
      color: 3,
      count: 4,
      correctAnswer: 4,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Circle,
      color: 4,
      count: 1,
      correctAnswer: 1,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Star,
      color: 3,
      count: 2,
      correctAnswer: 2,
      pattern: Pattern.Number,
    },
  ],
  [TrialRun.Air1]: [
    {
      shape: Shape.Plus,
      color: 1,
      count: 2,
      correctAnswer: 2,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Circle,
      color: 4,
      count: 4,
      correctAnswer: 4,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Plus,
      color: 3,
      count: 4,
      correctAnswer: 4,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Circle,
      color: 3,
      count: 4,
      correctAnswer: 4,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Triangle,
      color: 4,
      count: 1,
      correctAnswer: 1,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Plus,
      color: 1,
      count: 2,
      correctAnswer: 2,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Plus,
      color: 3,
      count: 3,
      correctAnswer: 3,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Circle,
      color: 3,
      count: 4,
      correctAnswer: 1,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Plus,
      color: 3,
      count: 3,
      correctAnswer: 3,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Triangle,
      color: 4,
      count: 4,
      correctAnswer: 2,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Star,
      color: 3,
      count: 4,
      correctAnswer: 4,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Circle,
      color: 3,
      count: 4,
      correctAnswer: 1,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Plus,
      color: 2,
      count: 1,
      correctAnswer: 2,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Circle,
      color: 2,
      count: 2,
      correctAnswer: 2,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Plus,
      color: 4,
      count: 2,
      correctAnswer: 4,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Triangle,
      color: 3,
      count: 4,
      correctAnswer: 3,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Circle,
      color: 4,
      count: 3,
      correctAnswer: 4,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Plus,
      color: 3,
      count: 1,
      correctAnswer: 3,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Circle,
      color: 1,
      count: 3,
      correctAnswer: 3,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Star,
      color: 2,
      count: 3,
      correctAnswer: 3,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Plus,
      color: 4,
      count: 1,
      correctAnswer: 1,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Circle,
      color: 4,
      count: 3,
      correctAnswer: 3,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Plus,
      color: 2,
      count: 1,
      correctAnswer: 1,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Star,
      color: 1,
      count: 4,
      correctAnswer: 4,
      pattern: Pattern.Number,
    },
  ],
  [TrialRun.Air2]: [
    {
      shape: Shape.Triangle,
      color: 2,
      count: 1,
      correctAnswer: 2,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Circle,
      color: 1,
      count: 2,
      correctAnswer: 1,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Circle,
      color: 4,
      count: 3,
      correctAnswer: 1,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Star,
      color: 4,
      count: 3,
      correctAnswer: 4,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Plus,
      color: 3,
      count: 1,
      correctAnswer: 3,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Star,
      color: 1,
      count: 3,
      correctAnswer: 4,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Star,
      color: 3,
      count: 2,
      correctAnswer: 3,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Plus,
      color: 1,
      count: 2,
      correctAnswer: 1,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Circle,
      color: 4,
      count: 2,
      correctAnswer: 4,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Triangle,
      color: 3,
      count: 4,
      correctAnswer: 3,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Plus,
      color: 4,
      count: 1,
      correctAnswer: 4,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Circle,
      color: 1,
      count: 3,
      correctAnswer: 1,
      pattern: Pattern.Color,
    },
    {
      shape: Shape.Star,
      color: 2,
      count: 3,
      correctAnswer: 4,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Circle,
      color: 1,
      count: 2,
      correctAnswer: 1,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Triangle,
      color: 2,
      count: 1,
      correctAnswer: 2,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Triangle,
      color: 4,
      count: 1,
      correctAnswer: 2,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Circle,
      color: 3,
      count: 2,
      correctAnswer: 1,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Circle,
      color: 2,
      count: 4,
      correctAnswer: 1,
      pattern: Pattern.Shape,
    },
    {
      shape: Shape.Plus,
      color: 4,
      count: 2,
      correctAnswer: 2,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Plus,
      color: 2,
      count: 2,
      correctAnswer: 2,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Triangle,
      color: 4,
      count: 3,
      correctAnswer: 3,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Plus,
      color: 1,
      count: 4,
      correctAnswer: 4,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Star,
      color: 3,
      count: 2,
      correctAnswer: 2,
      pattern: Pattern.Number,
    },
    {
      shape: Shape.Plus,
      color: 1,
      count: 4,
      correctAnswer: 4,
      pattern: Pattern.Number,
    },
  ],
};
